# Generated by Django 4.2.25 on 2025-10-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feathertree", "0002_story_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="previous_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_chapters",
                to="feathertree.chapter",
            ),
        ),
    ]
