# Generated by Django 4.2.25 on 2025-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feathertree', '0003_chapter_previous_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
