# Generated by Django 4.2.25 on 2025-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feathertree', '0004_chapter_submitted_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
