# Generated by Django 4.2.25 on 2025-11-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feathertree', '0005_chapter_feedback_chapter_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feathertree.story'),
        ),
    ]
