# Generated by Django 4.2.25 on 2025-11-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feathertree', '0006_alter_chapter_author_alter_chapter_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
